
services:

  mongo:
    image: cmerbruno/custom-mongo:v01
    restart: always
    container_name: mongo-scheduler-requisition 
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
    ports:
      - "2035:27017"
    volumes:
      - type: volume
        source: mongodb_data_volume
        target: /data/db
        
  mongo-express:
    image: cmerbruno/custom-mongo-express:v02
    container_name: mongo-express-scheduler-requisition
    restart: always
    ports:
      - "2036:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: changeme
      #ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
      ME_CONFIG_MONGODB_URL: mongo://mongoadmin:mongoadmin@mongo:2035/
      
    depends_on:
      - mongo

volumes:
  mongodb_data_volume:
    driver: local    
    